import { test, expect } from '@playwright/test';

test.describe('Contact Form E2E', () => {
    test('should successfully submit the contact form and show a success toast', async ({ page }) => {
        // 1. Navigate to the page
        await page.goto('/');

        // 2. Scroll to and wait for the contact section to be ready
        const contactTitle = page.locator('.contact-title');
        await contactTitle.scrollIntoViewIfNeeded();
        await expect(contactTitle).toBeVisible();

        // Ensure the form is visible
        const form = page.locator('.contact-form');
        await expect(form).toBeVisible();

        // 3. Fill the form using placeholder-based selectors
        await page.getByPlaceholder('Votre Nom').fill('Bastien Test');
        await page.getByPlaceholder('Votre Email').fill('test@playwright.dev');
        await page.getByPlaceholder('Sujet').fill('E2E Automated Test');
        await page.getByPlaceholder('Votre Message...').fill('This is an automated test message generated by Playwright.');

        // 4. Intercept the API call to avoid spamming the DB during tests
        await page.route('**/api/messages', async route => {
            expect(route.request().method()).toBe('POST');
            await route.fulfill({
                status: 201,
                contentType: 'application/json',
                body: JSON.stringify({ message: 'Message envoyé avec succès', id: 999 })
            });
        });

        // 5. Submit the form
        await page.click('button[type="submit"]');

        // 6. Verify the success toast appears
        const toast = page.locator('.toast.toast-success').first();
        await expect(toast).toBeVisible({ timeout: 5000 });
        await expect(toast).toContainText('Message envoyé avec succès');

        // 7. Verify the form was reset
        await expect(page.locator('input[name="name"]')).toHaveValue('');
    });
});
